global:
  external_labels:
    tenant: tenant-a

scrape_configs:
  - job_name: otel
    static_configs:
      - targets: ['localhost:8889']

# scrape_configs:
#   - job_name: tenant-a-apps
#     static_configs:
#       - targets:
#           - 10.10.0.11:8889
#           - 10.10.0.12:8889
